apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  labels:
    app: crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
       - name: crms
         image: prasanth202/crm:latest
         ports:
         - containerPort: 3000

