apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-app-deployment
  labels:
    app: crm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-app
  template:
    metadata:
      labels:
        app: crm-app
    spec:
      containers:
       - name: crm-app
         image: prasanth202/crm-image-demo1:latest
         ports:
         - containerPort: 80
       imagePullSecrets:
       - name: demo4

