
apiVersion: v1
kind: Service
metadata:
  name: crm-app-service
  labels:
    app: crm-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 81
  selector:
    app: crm-app
